name: ToolHive Pipeline

on:
  workflow_dispatch:
    inputs:
      deploy_crds:
        description: "CRDs"
        type: boolean
        required: true
        default: false
      deploy_operator:
        description: "Operator"
        type: boolean
        required: true
        default: false
      deploy_ui:
        description: "UI"
        type: boolean
        required: true
        default: false

jobs:
  crds:
    if: ${{ inputs.deploy_crds }}
    uses: ./.github/workflows/helm-deploy.yml
    with:
      chart_name: toolhive-operator-crds
      chart_url: oci://ghcr.io/stacklok/toolhive/toolhive-operator-crds
      version: "0.24.1"
      namespace: default
      values_file: ./values.crds.yml
    secrets:
      DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}

  operator:
    if: ${{ inputs.deploy_operator }}
    uses: ./.github/workflows/helm-deploy.yml
    with:
      chart_name: toolhive-operator
      chart_url: oci://ghcr.io/stacklok/toolhive/toolhive-operator
      version: "0.24.1"
      namespace: toolhive-system
      values_file: ./values.operator.yml
    secrets:
      DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}

  ui:
    if: ${{ inputs.deploy_ui }}
    uses: ./.github/workflows/helm-deploy.yml
    with:
      chart_name: toolhive-ui
      chart_url: ./helm/ui
      version: "1.0.0"
      namespace: toolhive-system
      values_file: ./values.ui.yml
    secrets:
      DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}