name: Operator Pipeline

# on:
#   workflow_dispatch:

# env:
#   RELEASE_NAME: n8n
#   NAMESPACE: n8n
#   VALUES_PATH: ./values.ingress.yml
#   HELM_CHART_PATH: ./helm/ingress

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ vars.DO_CLUSTER_NAME }}

      - name: Helm tool installer
        uses: azure/setup-helm@v4.2.0

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show CRDs
        run: |
          helm template \
            toolhive-operator-crds \
            oci://ghcr.io/stacklok/toolhive/toolhive-operator-crds
            --version 0.24.1
      - name: Deploy CRDs
        run: |
          helm upgrade --install \
            toolhive-operator-crds \
            oci://ghcr.io/stacklok/toolhive/toolhive-operator-crds
            --version 0.24.1

      - name: Show Operator
        run: |
          helm template \
            toolhive-operator \
            oci://ghcr.io/stacklok/toolhive/toolhive-operator \
            -n toolhive-system --create-namespace \
            --version 0.24.1
      - name: Deploy Operator
        run: |
          helm template \
            toolhive-operator \
            oci://ghcr.io/stacklok/toolhive/toolhive-operator \
            -n toolhive-system --create-namespace \
            --version 0.24.1